Disabled multithread on src/init/makefile because of compilation
errors some times:
bin/eposcc --library --gc-sections --nmagic -o scheduler_cpu_affinity_test scheduler_cpu_affinity_test.o
lib/pc_init_system.o: In function `global constructors keyed to _ZN4EPOS1S11init_systemE':
init_system.cc:(.text._GLOBAL__I__ZN4EPOS1S11init_systemE+0xe3): undefined reference to `EPOS::S::Thread::init()'
lib/libinit_ia32.a(system_init.o): In function `EPOS::S::System::init()':
system_init.cc:(.text._ZN4EPOS1S6System4initEv+0xd): undefined reference to `EPOS::S::Thread::init()'