Removed the parallel make from src/setup/makefile because it seems
to fail the compilation some times with:
make --print-directory all_multithread -j4
make[4]: Entering directory '/src/setup'
ia32-g++ -c --no-exceptions --no-rtti --no-use-cxa-atexit -std=c++0x -Wa,--32 -O0 -ggdb -nostdinc -Wall -Werror -fdata-sections -ffunction-sections -I/include pc_setup.cc
ia32-ld  -nostdlib -L/lib -Bstatic -L`ia32-gcc -ansi -c -Wa,--32 -print-file-name=` --omagic --section-start .init=0x00100000 -o pc_setup pc_setup.o -linit_ia32 -lmach_ia32 -larch_ia32 -lutil_ia32 -lgcc
pc_setup.o: In function `EPOS::S::PC_Setup::detect_pci(unsigned int*, unsigned int*)':
/src/setup/pc_setup.cc:958: undefined reference to `EPOS::S::PCI::header(EPOS::S::PCI_Common::Locator const&, EPOS::S::PCI_Common::Header*)'
makefile:22: recipe for target 'pc_setup' failed